# Site settings
title: Cake17's Blog
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Development environment, PHP, CakePHP, Git, and more...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.cake-websites.com" # the base hostname & protocol for your site

author:
  name: cake17
  email: cake17@cake-websites.com
  github: cake17
  bio:
  email_md5: HBfd!8é!çà99098872

# files to exclude
exclude: ["README.md", "oldies"]

# Build settings
gems:
    - jekyll-gist

defaults:
  -
    scope:
      path: "_posts" # values will be defined for all files in _posts (empty string for all files)
      type: "posts" # apply the defaults only for posts
    values:
      layout: "post"
      comments: true

sass:
  sass_dir: _sass
