# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

## Personal values
title: Cake17's Blog
description: Development environment, PHP, CakePHP, Git, and more...

author:
  name: cake17
  email: cake17@cake-websites.com
  github: cake17
  bio:
  email_md5: HBfd!8é!çà99098872

## Where things are
# source folder
source:  .
# destination folder
destination: ./_site
# plugins folder
plugins: ./_plugins
# layouts folder
layouts: ./_layouts
# data source folder
data_source: ./_data
# collections
collections: null
sass:
    sass_dir: assets/_sass

## Handling Reading
# Safe mode to false: plugins et symbolics links are authorized
safe:  false
include: [".htaccess"]
# files to exclude
exclude: ["README.md"]
keep_files:  [".git", ".svn"]
encoding:  "utf-8"
markdown_ext:  "markdown,mkdown,mkdn,mkd,md"
textile_ext: "textile"

## Filtering Content
show_drafts: null
limit_posts: 0
future:  true
unpublished: false

## Plugins
whitelist: []
gems:
  - jekyll-sitemap

## Conversion
markdown:  kramdown
kramdown:
  input: GFM # use Github Flavored Markdown
highlighter: pygments
lsi: false
excerpt_separator:  "\n\n"

## Serving
detach:  false
port:  4000
host:  0.0.0.0
baseurl: "" # does not include hostname

## Backwards-compatibility
relative_permalinks: false

## Outputting
permalink: date
paginate_path: /page:num
timezone:  "Europe/Paris"
quiet: false

## defaults var for all pages, posts & drafts
defaults:
  -
    scope:
      path: "_posts" # values will be defined for all files in _posts (empty string for all files)
      type: "posts" # apply the defaults only for posts
    values:
      layout: "post"
      comments: true
  -
    scope:
      path: "_drafts" # values will be defined for all files in _drafts (empty string for all files)
      type: "drafts" # apply the defaults only for drafts
    values:
      layout: "post"

# For RSS
rss_path: feed.xml
url: http://blog.cake-websites.com
tags_path: tags.html

paginate: 20
paginate_path: "page:num"
